version: "3.7"

services:
  node-red:
    build:
      context: ./build
      dockerfile: Dockerfile
    #image: nodered/node-red:latest
    environment:
      - TZ=Europe/Berlin
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
